name: 'Check linked work item to this PR (AB# with a valid work item id)'
on: # rebuild any PRs for main branch changes
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - main 
jobs:
  check-linked-work-item:
    name: Check linked work item to this PR
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-pr-is-linked-to-work-item@main
